### PR TITLE
Update french.ini : fix translation and encoding to ANSI

### PR DESCRIPTION
**Pull request by phenri**
fix translation and encoding to ANSI

### CODE REVIEW

**Comment by p060477** [comment]
are you able to use network bridged or only nat server?

**Comment by phenri** [comment]
@p060477 Yes both

**Comment by runarbu** [comment]
Thank you @phenri . This looks good to me. Merging.

**Comment by p060477** [comment]
hi runar a simple question still unanswered by you:
is now portable vb completely suitable with win 10?
i mean is useable the network BRIDGED?
or we are still forced to use only NAT server?
pls reply clearly!

**Pull request merged**
